### ISSUE TITLE
JSON Parsing Error When Building Attack Range After Fork: "Extra data: line 14 column 1 (char 4506)"

### ISSUE THREAD

**Issue by justsean9** [splunk/attack_range#1157]
**Problem**
I'm encountering a JSON parsing error when building Attack Range after forking the repository to implement SentinelOne as an installation path for AWS. The build fails during the Ansible playbook execution with an error indicating an issue with the splunk_vars.json file.

**Environment**
Previously using an older version before Packer was removed

OS: Using docker on windows

**Error Message**
When running the build, I receive the following errors:
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Extra data: line 14 column 1 (char 4506)
Syntax Error while loading YAML.
  did not find expected <document start>. did not find expected <document start>
  in "<unicode string>", line 14, column 1
The error appears to be in '/attack_range/terraform/ansible/vars/splunk_vars.json': line 14, column 1
The error specifically points to an issue with /attack_range/terraform/ansible/vars/splunk_vars.json at line 14, which appears to be near a closing brace followed by an unexpected EOF (End of File).
```
```

╷
│ Warning: Value for undeclared variable
│
│ The root module does not declare a variable named "local" but a value was found in file "/tmp/tmp877usc8x.tfvars.json". If you meant to use this value, add a "variable" block to the configuration.
│
│ To silence these warnings, use TF_VAR_... environment variables to provide certain "global" settings to all configurations in your organization. To reduce the verbosity of these warnings, use the
│ -compact-warnings option.
╵
╷
│ Error: local-exec provisioner error
│
│   with module.splunk-server.aws_instance.splunk-server[0],
│   on modules/splunk-server/resources.tf line 129, in resource "aws_instance" "splunk-server":
│  129:   provisioner "local-exec" {
│
│ Error running command 'ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu --private-key '/attack_range/root-64485.key' -i '18.117.105.93,' splunk_server.yml -e "@vars/splunk_vars.json"
│ ': exit status 4. Output: [WARNING]:  * Failed to parse 18.117.105.93, with host_list plugin: We were
│ unable to read either as JSON nor YAML, these are the errors we got from each:
│ JSON: Extra data: line 14 column 1 (char 4506)  Syntax Error while loading
│ YAML.   did not find expected <document start>. did not find expected <document
│ start>   in "<unicode string>", line 14, column 1  The error appears to be in
│ '/attack_range/terraform/ansible/vars/splunk_vars.json ': line 14, column 1,
│ but may be elsewhere in the file depending on the exact syntax problem.  The
│ offending line appears to be:  } EOF ^ here
│ [WARNING]: Unable to parse 18.117.105.93, as an inventory source
│ [WARNING]: No inventory was parsed, only implicit localhost is available
│ ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
│ JSON: Extra data: line 14 column 1 (char 4506)
│
│ Syntax Error while loading YAML.
│   did not find expected <document start>. did not find expected <document start>
│   in "<unicode string>", line 14, column 1
│
': line 14, column 1, but may'/attack_range/terraform/ansible/vars/splunk_vars.json
│ be elsewhere in the file depending on the exact syntax problem.
│
│ The offending line appears to be:
│
│ }
│ EOF
│ ^ here
│
╵
╷
│ Error: local-exec provisioner error
│
│   with module.windows-server.aws_instance.windows_server[0],
│   on modules/windows/resources.tf line 111, in resource "aws_instance" "windows_server":
│  111:   provisioner "local-exec" {
│
│ Error running command 'ansible-playbook -i '3.145.19.47,' windows.yml -e @vars/windows_vars_0.json': exit status 1. Output: [WARNING]:  * Failed to parse 3.145.19.47, with host_list plugin: Unable to
│ retrieve file contents Could not find or access
│ '/attack_range/terraform/ansible/vars/windows_vars_0.json' on the Ansible
│ Controller. If you are using a module and expect the file to exist on the
│ remote, see the remote_src option
│ [WARNING]: Unable to parse 3.145.19.47, as an inventory source
│ [WARNING]: No inventory was parsed, only implicit localhost is available
│ ERROR! Unable to retrieve file contents
│ Could not find or access '/attack_range/terraform/ansible/vars/windows_vars_0.json' on the Ansible Controller.
│ If you are using a module and expect the file to exist on the remote, see the remote_src option
│
╵

```
**Steps to Reproduce**

Forked the repository
Configured attack_range.yml as shown below
Ran the build command 

**Configuration Files**
attack_range.yml:
```yaml
general:
  cloud_provider: aws
  attack_range_password: [redacted]
  key_name: root-64485
  ip_whitelist: [removed]
  attack_range_name: ar-se
aws:
  region: us-east-2
  private_key_path: /attack_range/root-64485.key
windows_servers:
- hostname: ar-win-1
  windows_image: windows-server-2022
```

**Questions**

Could this be related to AMIs left over from before Packer was removed?

**Additional Context**
I'm working on implementing SentinelOne as an install path for AWS in this fork.  None of this is turned on for the original build.

**Comment by justsean9** [comment]
Reading into who attack_range.yml works.  And I am guessing it is somehow an issue with my new field?  

Specifically I added lines 19 and 20.  Running the proper splunk docker works fine 

```
  sentinelone_customer_ID: ""
  # SentinelOne Customer ID
```

attack_range_default.yml
```
general:
  attack_range_password: "Pl3ase-k1Ll-me:p"
  # Attack Range Master Password for all accounts in Attack Range.

  cloud_provider: "aws"
  # Cloud Provider: aws/azure/local

  key_name: "attack-range-key-pair"
  # The key name is the name of the AWS key pair and at the same time an unique identifier for Attack Ranges.

  attack_range_name: "ar"
  # Attack range Name let you build multiple Attack Ranges by changing this parameter.

  ip_whitelist: "0.0.0.0/0"
  # Blocks from which Attack Range machines can be reached.
  # This allow comma-separated blocks
  # ip_whitelist = 0.0.0.0/0,35.153.82.195/32

  sentinelone_customer_ID: ""
  # SentinelOne Customer ID

  crowdstrike_falcon: "0"
  # Enable/Disable CrowdStrike Falcon log forwarding to Splunk by setting this to 1 or 0.

  crowdstrike_customer_ID: ""
  crowdstrike_logs_region: ""
  crowdstrike_logs_access_key_id: ""
  crowdstrike_logs_secret_access_key: ""
  crowdstrike_logs_sqs_url: ""
  # All these fields are needed to automatically deploy a CrowdStrike Agent and ingest CrowdStrike Falcon logs into the Splunk Server.
  # See the chapter CrowdStrike Falcon in the docs page Attack Range Features.

  carbon_black_cloud: "0"
  # Enable/Disable VMWare Carbon Black Cloud log forwarding to Splunkby setting this to 1 or 0.

  carbon_black_cloud_company_code: ""
  carbon_black_cloud_s3_bucket: ""
  # All these fields are needed to automatically deploy a Carbon Black Agent and ingest Carbon Black logs into the Splunk Server.
  # See the chapter Carbon Black in the docs page Attack Range Features.

  cisco_secure_endpoint: "0"
  # Enable/Disable Cisco Secure Endpoint log forwarding to Splunk by setting this to 1 or 0.
  cisco_secure_endpoint_api_id: ""
  cisco_secure_endpoint_api_secret: ""
  cisco_secure_endpoint_api_host: "api.amp.cisco.com"
  # All these fields are needed to automatically ingest Cisco Secure Endpoint logs into the Splunk Server.

  install_contentctl: "0"
  # Install splunk/contentctl on linux servers

aws:
  region: "us-west-2"
  # Region used in AWS. This should be the same as the region configured in AWS CLI.

  private_key_path: "~/.ssh/id_rsa"
  # Path to your private key. This needs to match the public key uploaded to AWS.

  cloudtrail: "0"
  # Enable/Disable collection of CloudTrail logs by setting this to 1 or 0.

  cloudtrail_sqs_queue: "https://sqs.us-west-2.amazonaws.com/111111111111/cloudtrail-cloud-attack-range"
  # Cloudtrail SQS queue. See the chapter AWS CloudTrail in the docs page Attack Range Cloud.

  use_elastic_ips: "1"
  # Enable/disable usage of Elastic IPs by setting this to 1 or 0.

  use_remote_state: "0"
  # Store the state file in s3 and dynamoDB instead of local

  tf_remote_state_s3_bucket: "test"
  # Specify the already created S3 bucket in the same region

  tf_remote_state_dynamo_db_table: "test"
# Specify the already created DynamoDB table in the same region

azure:
  location: "West Europe"
  # Region used in Azure.

  subscription_id: "xxx"
  # Azure subscription ID.

  private_key_path: "~/.ssh/id_rsa"
  # Path to your private key.

  public_key_path: "~/.ssh/id_rsa.pub"
  # Path to your public key.

  azure_logging: "0"
  # Enable/Disable Azure logs and onboard them into the Splunk Server by setting this to 1 or 0.

  client_id: "xxx"
  client_secret: "xxx"
  tenant_id: "xxx"
  event_hub_name: "xxx"
  event_hub_host_name: "xxx"
# All these fields are needed to configure the Azure logs. See the chapter Azure Logs in the docs page Attack Range Cloud.

gcp:
  region: "europe-west3"
  # Region used in GCP. This should be the same as the region configured in GCP CLI.

  zone: "europe-west3-a"
  # Zone used in GCP. This should be the same as the zone configured in GCP CLI.

  project_id: "project-id"
  # Project ID used in GCP. This should be the same as the project ID configured in GCP CLI.

  public_key_path: "~/.ssh/id_rsa.pub"
  # Path to your public key.

  private_key_path: "~/.ssh/id_rsa"
  # Path to your private key.

  use_static_ip: "0"
  # Enable/disable usage of static IP by setting this to 1 or 0.

local:
  provider: "Virtual Box"
# Attack Range Local used Virtualbox and Vagrant to build the Attack Range.

splunk_server:

  install_es: "0"
  # Enable/Disable Enterprise Security by setting this to 1 or 0.

  splunk_es_app: "splunk-enterprise-security_731.spl"
  # File name of the Enterprise Security spl file. Needs to be located in the apps folder.

  s3_bucket_url: "https://attack-range-appbinaries.s3-us-west-2.amazonaws.com"
  # S3 bucket containing the Splunk Apps which will be installed in Attack Range.

  splunk_url: "https://download.splunk.com/products/splunk/releases/9.3.0/linux/splunk-9.3.0-51ccf43db5bd-Linux-x86_64.tgz"
  # Url to download Splunk Enterprise.

  splunk_uf_url: "https://download.splunk.com/products/universalforwarder/releases/9.3.0/linux/splunkforwarder-9.3.0-51ccf43db5bd-linux-2.6-amd64.deb"
  # Url to download Splunk Universal Forwarder Linux.

  splunk_uf_win_url: "https://download.splunk.com/products/universalforwarder/releases/9.3.0/windows/splunkforwarder-9.3.0-51ccf43db5bd-x64-release.msi"
  # Url to download Splunk Universal Forwarder Windows.

  splunk_apps:
    - TA-aurora-0.2.0.tar.gz
    - TA-osquery.tar.gz
    - app-for-circleci_011.tgz
    - cisco-secure-endpoint-(formerly-amp-for-endpoints)-cim-add-on_212.tgz
    - cisco-secure-endpoint-(formerly-amp-for-endpoints)_300.tgz
    - cisco-security-cloud_311.tgz
    - cisco-splunk-add-on-for-appdynamics_312.tgz
    - microsoft-defender-advanced-hunting-add-on-for-splunk_141.tgz
    - palo-alto-networks-add-on-for-splunk_813.tgz
    - punchcard---custom-visualization_150.tgz
    - python-for-scientific-computing-(for-linux-64-bit)_422.tgz
    - snort-3-json-alerts_105.tgz
    - snort-alert-for-splunk_112.tgz
    - splunk-add-on-for-amazon-web-services-(aws)_791.tgz
    - splunk-add-on-for-crowdstrike-fdr_204.tgz
    - splunk-add-on-for-github_310.tgz
    - splunk-add-on-for-google-workspace_303.tgz
    - splunk-add-on-for-microsoft-cloud-services_550.tgz
    - splunk-add-on-for-microsoft-office-365_480.tgz
    - splunk-add-on-for-microsoft-security_241.tgz
    - splunk-add-on-for-microsoft-windows_901.tgz
    - splunk-add-on-for-nginx_330.tgz
    - splunk-add-on-for-okta-identity-cloud_300.tgz
    - splunk-add-on-for-palo-alto-networks_200.tgz
    - splunk-add-on-for-sysmon-for-linux_100.tgz
    - splunk-add-on-for-sysmon_402.tgz
    - splunk-add-on-for-unix-and-linux_1000.tgz
    - splunk-app-for-stream_815.tgz
    - splunk-common-information-model-(cim)_603.tgz
    - splunk-es-content-update_540.tgz
    - splunk-machine-learning-toolkit_550.tgz
    - splunk-sankey-diagram---custom-visualization_160.tgz
    - splunk-security-essentials_381.tgz
    - splunk-ta-for-suricata_233.tgz
    - splunk-timeline---custom-visualization_162.tgz
    - splunk_attack_range_reporting-1.0.9.tar.gz
    - status-indicator---custom-visualization_150.tgz
    - ta-for-zeek_108.tgz
    - vmware-carbon-black-cloud_225.tgz
  # List of Splunk Apps to install on the Splunk Server

  byo_splunk: "0"
  # Enable/Disable Bring your own Splunk by setting this to 1 or 0.

  byo_splunk_ip: ""
  # Specify Splunk IP address when you enable BYO Splunk.

  ingest_bots3_data: "0"
  # Ingest BOTS data to Attack Range.

  install_dltk: "0"
# Install Deep Learning Toolkit.

phantom_server:
  phantom_server: "0"
  # Enable/Disable Phantom Server

  phantom_app: "splunk_soar-unpriv-6.3.1.178-d86bf7c2-el8-x86_64.tgz"
  # name of the Splunk SOAR package located in apps folder. 
  # aws, local: Make sure you use the RHEL 8 version which contains ....el8... in the file name
  # azure: Make sure you use the RHEL 7 version which contains ....el7... in the file name

  phantom_byo: "0"
  # Enable/Disable Bring your own Phantom

  phantom_byo_ip: ""
  # Specify Phantom IP address when you enabled byo phantom

  phantom_byo_api_token: ""
# Phantom Api Token

windows_servers_default:
  hostname: ar-win
  # Define the hostname for the Windows Server.

  windows_image: "windows-server-2019"
  # Name of the image of the Windows Server. 
  # allowd values: windows-server-2016, windows-server-2019, windows-server-2022

  create_domain: "0"
  # Create Domain will turn this Windows Server into a Domain Controller. Enable by setting this to 1.

  join_domain: "0"
  # Join a domain by setting this to 1 or 0.

  win_sysmon_config: "SwiftOnSecurity.xml"
  # Specify a Sysmon config located under configs/ .

  install_red_team_tools: "0"
  # Install different read team tools by setting this to 1 or 0.

  bad_blood: "0"
  # Install Bad Blood by setting this to 1 or 0.
  # More information in chapter Bad Blood under Attack Range Features.

  install_caldera_agent: "0"
  # Install a MITRE Caldera agent that connects to the Caldera Server.

  install_sentinelone: "0"
  # Install SentinelOne by setting this to 1.

  sentinelone_windows_agent: "WindowsSensor.exe"

  install_crowdstrike: "0"
  # Install CrowdStrike Falcon by setting this to 1.

  crowdstrike_windows_agent: "WindowsSensor.exe"
  # Name of the CrowdStrike Windows Agent stored in apps/ folder.

  install_carbon_black: "0"
  # Install Carbon Black Cloud by setting this to 1.

  carbon_black_windows_agent: "installer_vista_win7_win8-64-4.0.1.1428.msi"
  # Name of the Carbon Black Windows Agent stored in apps/ folder.

  install_cisco_secure_endpoint: "0"
  # Install Cisco Secure Endpoint by setting this to 1.

  cisco_secure_endpoint_windows_agent: "amp_Server.exe"
  # Name of the Cisco Secure Endpoint Windows Agent stored in apps/ folder.

  aurora_agent: "0"
  # Install Aurora Agent

  advanced_logging: "0"
  # Enable verbose windows security logs by setting this to 1.

linux_servers_default:
  hostname: ar-linux
  # Define the hostname for the Linux Server.

  sysmon_config: "SysMonLinux-CatchAll.xml"
# Specify a Sysmon config located under configs/ .

  install_crowdstrike: "0"
  # Install CrowdStrike Falcon by setting this to 1.

  crowdstrike_linux_agent: "falcon-sensor_7.18.0-17106_amd64.deb"
  # Name of the CrowdStrike Windows Agent stored in apps/ folder.

  install_cisco_secure_endpoint: "0"
  # Install Cisco Secure Endpoint by setting this to 1.

  cisco_secure_endpoint_linux_agent: "amp_Server_ubuntu-20-04-amd64.deb"
  # Name of the Cisco Secure Endpoint Linux Agent stored in apps/ folder.

  install_caldera_agent: "0"
  # Install a MITRE Caldera agent that connects to the Caldera Server.

kali_server:
  kali_server: "0"
# Enable Kali Server by setting this to 1.

nginx_server:
  nginx_server: "0"
  # Enable Nginx Server by setting this to 1.

  hostname: "nginx"
  # Specify the image used for Nginx Server.

  proxy_server_ip: "10.0.1.12"
  # Specify what ip to proxy.

  proxy_server_port: "8000"
# Specify what port to proxy.

zeek_server:
  zeek_server: "0"
  # Enable Zeek Server by setting this to 1.

snort_server:
  snort_server: "0"
  # Enable Snort Server by setting this to 1.

caldera_server:
  caldera_server: "0"
  # Enable MITRE Caldera Server by setting this to 1.

  hostname: "caldera"
  # Specify the image used for Caldera Server.

  # ------ Changing below this line could break MITRE Caldera -------------- #

  caldera_version: ""
  # MITRE Caldera Version to install (https://github.com/mitre/caldera/releases). Default: (left blank to pull latest)
  # caldera_version: "--branch 5.0.0"

  go_version: "1.23.3"
  # GO version to install (https://go.dev/dl/).

  nvm_version: "0.40.1"
  # NVM version to install (https://github.com/nvm-sh/nvm/releases).

  node_version: "22"
  # Node version to install (https://nodejs.org/en/download/package-manager).

  upx_version: "4.2.4"
  # UPX version to install (https://github.com/upx/upx/releases).

  private_ip: "10.0.1.70"
  # internal ip for the Caldera server (used for agent communication - no need to change).

simulation:
  atomic_red_team_repo: redcanaryco
  # Specify the repository owner for Atomic Red Team.

  atomic_red_team_branch: master
  # Specify the branch for Atomic Red Team.
```
