### ISSUE TITLE
Terraform error with "unsupported attribute" in build command.

### ISSUE THREAD

**Issue by G20100** [splunk/attack_range#697]
Hi,
I got an "unsupported attribute" error in the "attack_range.py build" command.
I enabled the WindowsDC and WindowsServer flug with attack_range.py configure command.

![image](https://user-images.githubusercontent.com/19428350/200555909-3a048cdf-fa15-4495-a2b8-620ef123bd75.png)

**Comment by ccl0utier** [comment]
Can confirm, I've run into the same issue.

**Comment by anshmax** [comment]
I am facing a similar issue - but its a remote-exec provisioner error. However, on a separate attempt - I have faced issues with building windows_ami

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/7013218/201214542-3f7db5ff-725c-4cb6-ad8f-8ccf78afcf4f.png)

**Comment by P4T12ICK** [comment]
hello, can you make sure that you have the latest version of develop branch and that you create a new attack_range.yml configuration file. A couple weeks ago the option windows_ami was renamed to windows_image. That could be the reason. The other important thing is that you need to define a list under windows_servers like this for example:
```
...
windows_servers:
  - hostname: ar-win-dc 
    image: windows-2016-v3-0-0
    create_domain: "1"
  - hostname: ar-win
    image: windows-2016-v3-0-0
    join_domain: "1"
...
```
Let me know if the problem still persists.
