### ISSUE TITLE
Error while installing the attack range by using dockers

### ISSUE THREAD

**Issue by Mohan-veera** [splunk/attack_range#755]
Hello team,

I am trying to install Splunk attack range simulator in Ubuntu 18.04 in AWS by using the dockers. During the installation the instances were created succesfully and there was no error generated. And after the Terraform initialization i am getting an error as below. Can anyone help me to resolve the issue ASAP...

![image](https://user-images.githubusercontent.com/125536973/219427597-22ca935f-fc77-42a0-9342-96a8ad02a344.png)

**Comment by gstefan-akryl** [comment]
Hi, 

Have same issue on AWS running from MacOS.

**Comment by patel-bhavin** [comment]
Can you share what your attack_range.yml config looks like? We haven't encountered this error before. Do you have aany stale .tf files in the `terraform/aws` directory? I would consider starting restarting from cloning the repo. Please always consider running destroy command before building any new resources. I am happy to jump on a zoom to help you troubleshoot this

**Comment by gstefan-akryl** [comment]
Standard, generated by attack_range configure. 

```
general:
  cloud_provider: aws
  attack_range_password: <password>
  use_prebuilt_images_with_packer: '1'
  key_name: <key_name>
  ip_whitelist: <...>
  range_name: ar
aws:
  private_key_path: .....<path>
  region: us-east-1
windows_servers:
- hostname: ar-win-1
  windows_image: windows-2016-v3-0-0
```
