### ISSUE TITLE
WinRM AWS connectivity issue

### ISSUE THREAD

**Issue by neokjames** [splunk/attack_range#813]
After working around a few of the other issues I've encountered during build, there appears to be another issue whereby the WinRM never successfully connects.

Using Ubuntu via WSL, latest codebase, trying to deploy to AWS

Seems to just continuously try to connect via WinRM but is never successful.

I've confirmed TCP 5985 is permitted on the Security Group as well.

```
module.windows-server.aws_instance.windows_server[0]: Still creating... [4m30s elapsed]
module.windows-server.aws_instance.windows_server[0] (remote-exec): Connecting to remote host via WinRM...
module.windows-server.aws_instance.windows_server[0] (remote-exec):   Host: 13.210.66.6
module.windows-server.aws_instance.windows_server[0] (remote-exec):   Port: 5985
module.windows-server.aws_instance.windows_server[0] (remote-exec):   User: Administrator
module.windows-server.aws_instance.windows_server[0] (remote-exec):   Password: true
module.windows-server.aws_instance.windows_server[0] (remote-exec):   HTTPS: false
module.windows-server.aws_instance.windows_server[0] (remote-exec):   Insecure: true
module.windows-server.aws_instance.windows_server[0] (remote-exec):   NTLM: false
module.windows-server.aws_instance.windows_server[0] (remote-exec):   CACert: false
```

if I interrupt the process, I get the following output:
```
╷
│ Error: remote-exec provisioner error
│
│   with module.windows-server.aws_instance.windows_server[0],
│   on modules/windows/resources.tf line 64, in resource "aws_instance" "windows_server":
│   64:   provisioner "remote-exec" {
│
│ interrupted - last error: http response error: 401 - invalid content type
```

**Comment by P4T12ICK** [comment]
I was not able to reproduce this behavior. Can you share your attack_range.yml file?

**Comment by neokjames** [comment]
Sure, nothing special, just AWS with 2 Windows servers.

```
general:
  cloud_provider: aws
  attack_range_password: infected
  use_prebuilt_images_with_packer: '1'
  key_name: root-70344
  ip_whitelist: 0.0.0.0/0
  attack_range_name: ar
aws:
  private_key_path: /attack_range/root-70344.key
  region: ap-southeast-2
windows_servers:
- hostname: ar-win-dc
  windows_image: windows-2016-v3-0-0
  create_domain: '1'
- hostname: ar-win-2
  windows_image: windows-2016-v3-0-0
  join_domain: '1'
  install_red_team_tools: '1'
```
