### ISSUE TITLE
Task Contentctl : Install required system packages failed

### ISSUE THREAD

**Issue by b33kar** [splunk/attack_range#814]
Local build on Ubuntu 22.04

TASK [contentctl : Install required system packages] ***************************
fatal: [ar-splunk-attack-range-key-pair-ar]: FAILED! => {"msg": "The conditional check '(use_prebuilt_images_with_packer == \"0\") and (install_contentctl == \"1\")' failed. The error was: error while evaluating conditional ((use_prebuilt_images_with_packer == \"0\") and (install_contentctl == \"1\")): 'install_contentctl' is undefined\n\nThe error appears to be in '/home/trax/attack_range/packer/ansible/roles/contentctl/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install required system packages\n  ^ here\n"}

**Comment by 0xtamsee1** [comment]
I'm facing the same issue ever since contentctl was added to ansible playbook.

**Comment by P4T12ICK** [comment]
Let me check. Thank you for reporting it.

**Comment by P4T12ICK** [comment]
Can you share your attack_range.yml configuration?

**Comment by b33kar** [comment]
```
general:
  cloud_provider: local
  attack_range_password: Dxw5z0f9DvOfPVbcmqr
local: {}
windows_servers:
- hostname: ar-win-dc
  windows_image: windows-2019-v3-0-0
  create_domain: '1'
  install_red_team_tools: '1'
  bad_blood: '1'
linux_servers:
- hostname: ar-linux
```
