### ISSUE TITLE
Initialization of windows server variables does not consider multiple servers

### ISSUE THREAD

**Issue by bl4ckOut** [splunk/attack_range#992]
Hi.. I have the following attack_range.yml after configuring two windows servers:

```
[...]
windows_servers:
- hostname: ar-win-dc
  windows_image: windows-server-2016
  create_domain: '1'
  bad_blood: '1'
- hostname: ar-win-2
  windows_image: windows-server-2016
  join_domain: '1'
  install_red_team_tools: '1'
[...]
```

As I understand it, Vagrant assembles the Vagrantfile "..\vagrant\Vagrantfile" based on the template in "..\vagrant\windows_server\Vagrantfile" for the windows servers.

This means that two entries for the windows servers are stored in the ".\vagrant\Vagrantfile", one for the DC “ar-win-dc” and one for “ar-win-2”.

However, the configured variables of the windows servers are then written to the same JSON file ("..\vagrant\windows_vars.json"), because both entries in the merged Vagrantfile include:
```
[...]
File.write("windows_vars.json", JSON.pretty_generate(windows_vars))
[...]
```

During the build process, the variables of the first server (DC) are now overwritten by the second server. This means, for example, that the build process is aborted because “join_domain” has been set to 1 and the DC attempts to join a domain that has not yet been created. 

It seems that the handling of variables for multiple windows servers is completely missing or am I missing something?
